# Generated by Django 6.0.5 on 2026-05-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('materia', 'estudiante', 'fecha')},
        ),
        migrations.CreateModel(
            name='ActividadPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('entregada', 'Entregada')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.materia')),
            ],
            options={
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='ReporteComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_falta', models.CharField(choices=[('irrespeto', 'Irrespeto al docente o compañeros'), ('bullying', 'Bullying / acoso'), ('indisciplina', 'Indisciplina en clase'), ('trampa', 'Trampa / deshonestidad académica'), ('daño', 'Daño a propiedad'), ('lenguaje', 'Lenguaje inapropiado'), ('otro', 'Otro')], max_length=30)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], default='leve', max_length=10)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.materia')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
