# Generated by Django 6.0.5 on 2026-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estudiante_foto_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorianota',
            options={'ordering': ['periodo', 'orden']},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reportecomportamiento',
            name='gravedad',
        ),
        migrations.AddField(
            model_name='actividadpendiente',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')], default=1),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')], default=1),
        ),
        migrations.AddField(
            model_name='categorianota',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')], default=1),
        ),
        migrations.AddField(
            model_name='reportecomportamiento',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')], default=1),
        ),
        migrations.AlterField(
            model_name='actividadpendiente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada')], default='pendiente', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('materia', 'estudiante', 'periodo', 'fecha')},
        ),
    ]
