# Generated by Django 6.0.5 on 2026-05-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categorianota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
