# Generated by Django 6.0.5 on 2026-05-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categorianota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorianota',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='participativo',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante destaca por su participación', verbose_name='Estudiante participativo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='razon_inactivo',
            field=models.TextField(blank=True, default='', help_text='Ej: Retiro voluntario, traslado, etc.', verbose_name='Razón de inactividad'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
