# Generated by Django 6.0.5 on 2026-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categorianota_descripcion_estudiante_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='grado',
            name='orden',
            field=models.IntegerField(default=0, help_text='Para ordenar los grados (0, 1, 2...)'),
        ),
    ]
